### ISSUE TITLE
react-boilerplate

### ISSUE THREAD

**Issue by kopax** [3dmind/jest-sonar-reporter#10]
I am using react-boilerplate that use jest and istanbul for coverage.

I have tried to run sonnar scanner and I encounter trouble to get the proper configuration.

Would you mind showing an example of sonar configuration on [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate/) project?

**Comment by 3dmind** [comment]
The important part is to tell Sonar where to find the coverage information.
Use `sonar.javascript.lcov.reportPaths` in the project properties to specify the path of the stored `lcov.info` file. For example: `sonar.javascript.lcov.reportPaths=coverage/lcov.info`
Jest stores coverage information in `coverage/lcov.info`.

**Comment by kopax** [comment]
Your plugin work well and the documentation helped. I can see it is quite recent, thank you for sharing it.
