### ISSUE TITLE
Does this plugin even work anymore?

### ISSUE THREAD

**Issue by adamchenwei** [3dmind/jest-sonar-reporter#16]
1. SonarQube 6.3
2. Followed the exact instruction
3. getting error as following

![screen shot 2018-01-03 at 4 25 48 pm](https://user-images.githubusercontent.com/4201698/34540514-d34b2bd4-f0a2-11e7-8901-3b886d2f4fcf.png)

What inside `Header/index.test.js` is following code

```
import React from 'react';
import renderer from 'react-test-renderer';
import Header from './index';

describe('Header Container', () => {
  test('renders as expected', () => {
    const tree = renderer.create(<Header />).toJSON();
    expect(tree).toMatchSnapshot();
  });

  describe('When Unauthorized', () => {
    test('unauthorized', () => {
      const tree = renderer.create(<Header roles={{}} />).toJSON();
      expect(tree).toMatchSnapshot();
    });
  });
});

```

Is there anything I missed that maybe not inside the document?

**Comment by 3dmind** [comment]
Hi @adamchenwei 

Please check if the configuration options `sonar.tests` and `sonar.test.inclusions` are set correctly in the `sonar-project.properties` file.

Please also have look at the SonarQube [documentation](https://docs.sonarqube.org/display/SONAR/Analysis+Parameters).

**Comment by adamchenwei** [comment]
too much hussle lol I used jest with SonarQube and its SonarJS with JS config directly. worked. without jest-sonar-reporter. But thanks for making this!
