### ISSUE TITLE
Configuration for relative or absolute path in report

### ISSUE THREAD

**Issue by daniyel** [3dmind/jest-sonar-reporter#18]
Hi.

First of all I do not know, if this is an issue, I would say it is more of a feature request. I need a configuration option where I can define, if path for file element in XML report uses absolute or relative path. In this moment the path is absolute and I had a problem with that, such that Sonar Qube would not import my JUnit reports, because the path would not match with the path that I set for tests and source in Sonar Qube properties.

### Expected behaviour
Config option to set, if path for file element in report should be either relative or absolute.

### Actual behaviour
It is always absolute path.

### Steps to reproduce the behaviour
Run jest test runner with jest-sonar-reporter inside a AWS CodeBuild.

Best regards.

**Comment by daniyel** [comment]
Hi.

I already made as you recommended to do a fork and then a pull request. Here is the commit: https://github.com/3dmind/jest-sonar-reporter/commit/f6a98c5aaab907d1c339a0434f2218f6e04b9883. But however I am having problem with Travis. It seems he cannot find sonar-scanner command.


```
The command "sonar-scanner" exited with 127.
cache.2
store build cache
0.00s
2.74schanges detected, packing new archive
uploading archive
Done. Your build exited with 1.
```

Best regards.

**Comment by 3dmind** [comment]
Hi.

Thanks for your work and pull request. I will have a look and investigate into the Travis CI issue.

Best regards.

**Comment by StefanKoenen** [comment]
@3dmind Any update on this issue? I think I have the same issue, absolute VS relative paths...

**Comment by SanderElias** [comment]
@3dmind I'm also running into this.
What makes it strange is that HTML and TS seem to get a different path in the `lcov.info` while they are in the same folder.

```
SF:C:\projects\myProject\app-shell\src\app\app-shell\as-main\as-main.component.html
SF:C:\projects\myProject\app-shell\src\app\app-shell\as-main\app\app-shell\as-main\as-main.component.ts
```
(removed irrelevant lines)
I can not find a cause for that anywhere in my config.

**Comment by agcalc** [comment]
It would be really great if this could be merged. As a workaround I'm doing post-processing on the generated report to make the paths relative.

**Comment by jimmux** [comment]
Bump. We are also relying on post-processing the report to relative paths.
