### ISSUE TITLE
Currently the package.json is used for configuration, would love to be able to use jest.config or alternate file

### ISSUE THREAD

**Issue by iangregsondev** [3dmind/jest-sonar-reporter#22]
I was wondering if the following would be possible ?

### Expected behaviour
To use either the jest.config or alternative config file for configuring the plug, so to keep the package.json nice and clean.

### Actual behaviour
Currently the package.json is used for configuration, would love to be able to use jest.config or alternate file

**Comment by abramenal** [comment]
Would love that as well!

**Comment by cpasslack** [comment]
Would love this too. We use nx (https://nx.dev/) as a monorepo with only one package.json but different jest.configs for every app and lib. A configuration with jest.config would make some things easier. The solution with the node environment variable works, but is not optimal for our use case.

**Comment by dianjuar** [comment]
@cpasslack I have the same problem, Validation Warning says:

```
Unknown option "jestSonar" with value {"indent": 4, "reportFile": "demo-test-reporter.xml", "reportPath": "reports"} was found.
  This is probably a typing mistake. Fixing it will remove this message.
```

![image](https://user-images.githubusercontent.com/7026066/63474670-97c89700-c43f-11e9-9b38-373dc3ef1a8b.png)
