### ISSUE TITLE
test-report.xml only giving Generic Execution data and no Generic Coverage data...

### ISSUE THREAD

**Issue by Bmahecha123** [3dmind/jest-sonar-reporter#26]
### Expected behaviour
I would expect Jest-Sonar-Reporter to generate a full Generic Test Data report as the readme suggests.

### Actual behaviour
Generating a test-report.xml file which only contains Generic Execution data. Was expecting Generic Coverage information as well.

### Steps to reproduce the behaviour
Install plugin, generate test-report.xml and inspect the xml file to see that it only includes Generic Execution as outlined by https://docs.sonarqube.org/display/SONAR/Generic+Test+Data

**Comment by vasilisp89** [comment]
I am having the same issue. I want to reproduce the coverage data of my tests in the sonar report as well

**Comment by KIRY4** [comment]
Any updates?

**Comment by rabend** [comment]
I solved the coverage issue in this way:
First, configure jest to use jest-sonar-reporter as a test result processor and also generate an lcov file for coverage in jest.config.js
`coverageDirectory: '<rootDir>/reports/jest,'
coverageReporters: ['html', 'json', 'text-summary', 'lcov'],
testResultsProcessor: 'jest-sonar-reporter'`

Then, tell sonar where it can find you execution and coverage reports in sonar-project.properties:
`sonar.testExecutionReportPaths=reports/test-report.xml
sonar.javascript.lcov.reportPaths=reports/lcov.info`

Lastly and most importantly: run jest with the coverage flag:
`jest --coverage`

Then you can run your sonar scanner and see the results in sonarqube/sonarcloud
