### ISSUE TITLE
report folder is not generating

### ISSUE THREAD

**Issue by WalkOffEarth** [3dmind/jest-sonar-reporter#27]
### Expected behaviour

report folder should created with xml

### Actual behaviour

report folder is not creating

### Steps to reproduce the behaviour
done this configuration 

package.json

{
"scripts": {
"test": "jest --coverage -u",
},
"devDependencies": {
     "jest": "^22.4.2",
    "jest-sonar-reporter": "^2.0.0",
},
"jest": {
    "testEnvironment": "node",
    "testResultsProcessor": "jest-sonar-reporter"
  },
  "jestSonar": {
    "reportPath": "reports",
    "reportFile": "test-report.xml",
    "indent": 4
  }
}

sonar.project.properties

sonar.language=js
sonar.sources=src
sonar.tests=src
sonar.sourceEncoding=UTF-8

sonar.test.inclusions=src/**/*.spec.js,src/**/*.spec.jsx,src/**/*.test.js,src/**/*.test.jsx

sonar.testExecutionReportPaths=reports/test-report.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info

and doing npm run test

anything which i am missing

**Comment by zerbfra** [comment]
Avoid this plugin,
use directly jest that has instabul integrated.

My `jest.config.js`:
```
module.exports = {
  [....]
  collectCoverage: true,
  coverageDirectory: './.coverage',
};
```

Then in `sonar-project.properties`:
```
[...]
# Path is relative to the sonar-project.properties file. Replace "" by "/" on Windows.
# This property is optional if sonar.modules is set.
sonar.tests=./__tests__

# Typescript LCOV
sonar.typescript.lcov.reportPaths=./.coverage/lcov.info
[...]
```

**Comment by rasheedhere** [comment]
Use `testResultsProcessor: "jest-sonar-reporter"` config in the jest.config.js

It worked for me. Cheers!
