### ISSUE TITLE
Support for reporters?

### ISSUE THREAD

**Issue by ghost** [3dmind/jest-sonar-reporter#29]
Is there any planned support for the jest [reporters](https://jestjs.io/docs/en/configuration#reporters-array-modulename-modulename-options) property. I hear there is talk that they will start deprecating testResultsProcessor soon in favor of reporters?

### Expected behaviour

As a test I placed `jest-sonar-reporter` in the reporters field of the jest config and expected it to work.

### Actual behaviour

The reporter fails to initialize with the following exception:

```
Error: An error occurred while adding the reporter at path "node_modules/jest-sonar-reporter/index.js".Reporter is not a constructor
```

### Steps to reproduce the behaviour

Place `jest-sonar-reporter` in the reporters array instead of testResultsProcessor

**Comment by ghost** [comment]
Did some quick digging into this:

looks like if you change reporter.js to this:

```JavaScript
'use strict'

const fs = require('fs')
const path = require('path')
const xml = require('xml')
const getPackageData = require('./utils/getPackageData')
const getConfig = require('./utils/getConfig')
const xmlIndent = require('./utils/xmlIndent')
const testExecutions = require('./xml/testExecutions')
const getDefaultConfig = require('./getDefaultConfig')

const root = process.cwd()
const packageData = getPackageData(root)
const config = Object.assign({}, getDefaultConfig(root), getConfig(packageData, process.env.NODE_ENV))

module.exports = function Reporter(globalConfig, options) {
  this.onRunComplete = (context, results) => {
    const report = xml(testExecutions(results, config.sonar56x), { declaration: true, indent: xmlIndent(config.indent) })

    if (!fs.existsSync(config.reportPath)) {
      fs.mkdirSync(config.reportPath)
    }

    const reportFile = path.join(config.reportPath, config.reportFile)
    fs.writeFileSync(reportFile, report)

    if (process.env.DEBUG) {
      fs.writeFileSync('debug.json', JSON.stringify(results, null, 2))
    }

    return results
  }
}
```

it would work as expected. Though this would break a testResultProcessor field so not sure how you would want to handle that. Hope this helps.

**Comment by fiedlr** [comment]
Any update on this?

**Comment by fiedlr** [comment]
@AHumanFromCA @3dmind Any updates on this?

**Comment by ghost** [comment]
@fiedlr I see that a PR has been opened that should address this issue but other than that I don't have anything else to mention. I have been reassigned to a different project so even if this were to be resolved, I wouldn't be able to test it out.
