### ISSUE TITLE
Parsing error due to invalid character

### ISSUE THREAD

**Issue by tinovyatkin** [3dmind/jest-sonar-reporter#30]
Sonar fails on attempt to parse generate file:

```sh
10:23:06.365 ERROR: Error during parsing of generic test execution report '/root/repo/reports/test-reporter.xml'. Look at the SonarQube documentation to know the expected XML format.
10:23:06.365 ERROR: Caused by: Illegal character ((CTRL-CHAR, code 27))
 at [row,col {unknown-source}]: [13,61]
```

**Comment by Akaryatrh** [comment]
Just encountered the exact same issue @tinovyatkin , did you finally fixed it somehow?

**Comment by tinovyatkin** [comment]
Nope, waiting for fix

**Comment by Akaryatrh** [comment]
@tinovyatkin I believe the issue comes from local environment while a colleague of mine is able to generate an XML report without any character issues by running the same tools.

**Comment by tinovyatkin** [comment]
@Akaryatrh you mean
![2305863_0](https://user-images.githubusercontent.com/5350898/61420272-b632f400-a8cf-11e9-8cf8-4eddc7d20e94.jpg)

**Comment by Akaryatrh** [comment]
Ah ah yeah @tinovyatkin but it also works on a CI environment :)
