### ISSUE TITLE
Error when running jest without coverage (no folder)

### ISSUE THREAD

**Issue by shmaram** [3dmind/jest-sonar-reporter#33]
### Expected behaviour
To be able to run jest without coverage and without jest-sonar-reporter another

### Actual behaviour
jest-sonar-reporter throws an error for no folder was found 

![image](https://user-images.githubusercontent.com/12017112/64942371-8a9d9d00-d871-11e9-9859-b411a7318071.png)

### Steps to reproduce the behaviour
When running jest with without coverage, no coverage folder is created and then jest-sonar-reporter throws an error for no folder was found

**Comment by ameersami** [comment]
@shmaram this error seems correct, jest-sonar-reporter need the various coverage files generated by jest to generate the report

**Comment by shmaram** [comment]
@ameersami , I understand that. 
The problem is that once I I define this package in my code I unable to run jest in localhost without the jest coverage flag. 
I would like to have the ability to use this package according to my mode (dev or production)
